# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5a9dafadf1835c375e8ba64dbbec45599fb50cdb2999c5ef8f27d8bcf0ba50f5a34c780429d7646cf929bff3766616d47280ea2eaf62ff3745c5d1e979103243

test:
  secret_key_base: aee118f504a601c020e582ed9c598178a3552068af9ffa7876b2e242372840ec25f34e6e237e3198020ba1061c0f9877f246c926862152bd766555296246dfd3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
